[Feat] 프로필뷰 첫 페이지 기초 UI
DeveloperAcademy-POSTECH/MacC-Team-NoPower pull request #9
Opened 2022-10-18 07:36 UTC by heokyeol

## 관련 이슈들
- #1 

## 작업 내용
- 컬렉션뷰 이용, 단순 UI 작업
- 각 흰색 박스는 다른 섹션이며, 셀은 한 파일에 서로 다른 identifier으로 적용
- 유저 이름, 카페 이름은 목데이터 이용 / 상태메시지, 시간 등은 변수에 직접 하드코딩

- 다음 피알은 통계 그래프 입니다. (주차 넘기기 구현 가능하면 거기까지, 일단 feature만)

## 리뷰 노트
- 오토레이아웃을 하던방식대로 했는데 개선점이 있을 것 같습니다

## 스크린샷(UX의 경우 gif)
<img width="300" alt="스크린샷 2022-10-18 10 07 07" src="https://user-images.githubusercontent.com/70618615/196365872-203234ae-4b25-42d6-951b-a64d791ab268.png">

## Reference
- https://stackoverflow.com/questions/31314412/how-to-resize-image-in-swift
- 이미지 리사이즈 함수 인용 (resizeImage)

## 체크리스트
- [ ] 올바른 브랜치로 PR을 날리고 있는지 더블CHECK!
- [ ] 확인을 위해 바꾼 SceneDelegate.swift를 원래의 상태로 바꾸어 놓으셨나요?
- [ ] 불필요한 주석과 프린트문은 삭제가 되었나요?

2022-10-18 07:42 UTC, hardworking-nomad commented on BNomad/Application/SceneDelegate.swift
> +        window?.rootViewController = ProfileViewController()
P1: 커밋할 때 이 부분은 원래의 ViewCon으로 복귀시키거나 아예 이 파일을 커밋, PR 대상에서 제외하고 올려야 합니닷

2022-10-18 07:46 UTC, hardworking-nomad commented on BNomad/View/ProfileView/ProfileViewCell.swift
> +        statusLabel.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -20).isActive = true
P3: UIView Extension의 각각의 addSubview마다 Anchor 한 줄로 축약이 가능합니다. (저도 이 부분 코멘트 받고 수정했습니다 ㅋㅋ)

2022-10-18 07:53 UTC, hardworking-nomad commented on BNomad/View/ProfileView/ProfileViewCell.swift
> +class ProfileViewCell1: UICollectionViewCell {
ProfileViewCell1 이라는 이름보다 SelfUserInfo 등의 이름으로 지정하는 게 가독성이 높을 것 같습니다.
(자기 카드는 Self, 타인의 카드는 그냥 UserInfo..?)

마찬가지로 아래의 ProfileViewCell2는 특정 공간의 개별 방문을 축약하는 정보니까 그에 맞는 이름으로..
VisitingInfoCard라든지 어울리는 이름 고민이 필요합니다.

2022-10-18 08:05 UTC, sunshiningsoo requested changes
SceneDelegate 수정과 ProfileViewCell1 과 같은 것만 피해주면 좋을 것 같아요~
글에 올라온 이미지가 너무 커서 img width 300으로 맞춰주면 좋을 것 같습니다
고생하셨슴다🫡

2022-10-18 08:05 UTC, sunshiningsoo commented on BNomad/View/ProfileView/ProfileViewController.swift
> +        }
[P3] static identifier 의견과 동일합니다🙃

2022-10-18 08:05 UTC, sunshiningsoo commented on BNomad/View/ProfileView/ProfileViewController.swift
> +
[P3] //MARK: - UICollectionViewDelegateFlowLayout 작성하면 더 가독성이 좋을 것 같아요~!

2022-10-18 08:36 UTC, sunshiningsoo commented on BNomad/View/ProfileView/ProfileViewCell.swift
> +import SwiftUI
[P5] SwiftUI의 활용이 되고 있나요..??🤔 지워도 문제 없다면 지워도 괜찮을 것 같습니다

2022-10-18 08:36 UTC, sunshiningsoo commented on BNomad/View/ProfileView/ProfileViewCell.swift
> +
[P3] 한파일에 다 넣기보다, 2개로 파일 분기해주는 것이 좋을 것 같아요

2022-10-19 00:31 UTC, heokyeol commented on BNomad/Application/SceneDelegate.swift
> +        window?.rootViewController = ProfileViewController()
주의하겠습니닷 수정했습니다

2022-10-19 00:33 UTC, heokyeol commented on BNomad/Utils/Extensions/UIColor+Extension.swift
>  }
수정했습니다

2022-10-19 00:33 UTC, heokyeol commented on BNomad/View/ProfileView/ProfileViewCell.swift
> +import SwiftUI
?? 왜 들어갔는지 모르겠네요 수정했습니닷

2022-10-19 00:35 UTC, heokyeol commented on BNomad/View/ProfileView/ProfileViewCell.swift
> +class ProfileViewCell1: UICollectionViewCell {
감사합니다 다만 컬렉션뷰에서 전환 가능성이 있어서 해당 뷰 최종 피알때 꼭 반영하도록 하겠습니닷

2022-10-19 00:36 UTC, heokyeol commented on BNomad/View/ProfileView/ProfileViewCell.swift
> +        statusLabel.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -20).isActive = true
감사합니닷 혹시 anchor에서 constant는 어떻게 설정할 수 있나요 !?

2022-10-19 00:37 UTC, heokyeol commented on BNomad/View/ProfileView/ProfileViewCell.swift
> +
감사합니다 반영하겠습니닷

2022-10-19 01:02 UTC, sunshiningsoo approved these changes

2022-10-19 01:03 UTC, merged